// Jest configuration
// Reference: https://jestjs.io/docs/configuration

module.exports = {
  testMatch: [
    '**/test/*.js'
  ],
  testPathIgnorePatterns: [
    '<rootDir>/test/helpers.js'
  ],
  setupFilesAfterEnv: [
    '<rootDir>/test/helpers.js'
  ],
  watchPathIgnorePatterns: [
    // Ignore the output generated by plugin tests
    // when watching for changes to avoid the test
    // runner continuously re-running tests
    '<rootDir>/test/output'
  ]
};
